name: ProTiler - Build All Platforms

on: workflow_dispatch

jobs:
  buildForAllSupportedPlatforms:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
          - StandaloneWindows # Build a Windows standalone.
          - StandaloneWindows64 # Build a Windows 64-bit standalone.
          - StandaloneLinux64 # Build a Linux 64-bit standalone.
          - iOS # Build an iOS player.
          - Android # Build an Android .apk standalone app.
          - WebGL # WebGL.
        projectPath:
          - ProTiler
    
    steps:
      # Checkout
      - name: Checkout Files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          
      # Cache
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
            
      # Build
      - name: Build ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
      
      # Output
      - name: Create Output for ${{ matrix.targetPlatform }}
        uses: actions/upload-artifact@v2
        with:
          name: Build-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          path: Builds/${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          