name: ProTiler - Build WebGL

on: workflow_dispatch

jobs:

  testAllModes:
    name: ${{ matrix.unityVersion }}-${{ matrix.testMode }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ProTiler
        unityVersion:
          - 2021.2.0f1
        testMode:
          - EditMode
          - PlayMode
          
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          lfs: true
          
      # Cache
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-Tests
          restore-keys: |
            Library-${{ matrix.projectPath }}-Tests

      # Run Tests
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          unityVersion: ${{ matrix.unityVersion }}
          artifactsPath: artifacts-${{ matrix.unityVersion }}-${{ matrix.testMode }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.unityVersion }}-${{ matrix.testMode }} Test Results
          coverageOptions: 'useProjectSettings;generateHtmlReport;generateBadgeReport;generateAdditionalMetrics'
      
      # Artifacts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results for ${{ matrix.unityVersion }}-${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results for ${{ matrix.unityVersion }}-${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}

  buildAllSupportedPlatforms:
    needs: testAllModes
    name: ${{ matrix.unityVersion }}-${{ matrix.targetPlatform }} Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ProTiler
        unityVersion:
          - 2022.2.15f1
          - 2022.2.0f1
          - 2022.1.0f1
          - 2021.3.0f1
          - 2021.2.0f1
        targetPlatform:
          - WebGL
    
    steps:
      # Checkout
      - name: Checkout Files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      # Cache
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
            Library-${{ matrix.projectPath }}-

      # Build
      - name: Build ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}
          versioning: Semantic
          buildName: ${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          buildsPath: build/${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
      
      # Output
      - name: Create Output for ${{ matrix.targetPlatform }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          path: build/${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
