name: Build Single - ProTiler

on: workflow_dispatch

jobs:

  buildAllSupportedPlatforms:
    name: ${{ matrix.unityVersion }}-${{ matrix.targetPlatform }} Build
    runs-on: ubuntu-latest
    environment: BuildProTiler
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ${{ vars.PROJECT_PATH }}
        unityVersion:
          - ${{ vars.BUILD_SINGLE_UNITYVERSION }}
        targetPlatform: 
          - ${{ vars.BUILD_SINGLE_TARGETPLATFORM }}
    
    steps:
      # Checkout
      - name: Checkout Files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      # Cache
      - name: Cache Library
        uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles('ProTiler/Assets/**', 'ProTiler/Packages/**', 'ProTiler/ProjectSettings/**') }}
          restore-keys: |
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ hashFiles('ProTiler/Assets/**', 'ProTiler/Packages/**', 'ProTiler/ProjectSettings/**') }}
            Library-${{ matrix.projectPath }}-${{ matrix.targetPlatform }}
            Library-${{ matrix.projectPath }}-Tests

      # Build
      - name: Build ${{ matrix.targetPlatform }}
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: ${{ matrix.unityVersion }}
          versioning: Semantic
          buildName: ${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          buildsPath: build/${{ matrix.projectPath }}-${{ matrix.unityVersion }}
          buildMethod: CodeSmile.Editor.CI.BuildScript.Build
      
      # Output
      - name: Create Output for ${{ matrix.targetPlatform }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.projectPath }}-${{ matrix.targetPlatform }}-${{ matrix.unityVersion }}
          path: build/${{ matrix.projectPath }}-${{ matrix.unityVersion }}
