name: ProTiler - Run All Tests

on: workflow_dispatch

jobs:

  testAllModes:
    name: ${{ matrix.testMode }}-${{ matrix.unityVersion }} Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectPath:
          - ProTiler
        unityVersion:
          - 2022.2.0f1
          - 2022.1.0f1
          - 2021.3.0f1
          - 2021.2.0f1
          - 2021.1.0f1
        testMode:
          - EditMode
          - PlayMode
    steps:
      # Checkout
      - uses: actions/checkout@v3
        with:
          lfs: true
          
      # Cache
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.projectPath }}-Tests
          restore-keys: |
            Library-${{ matrix.projectPath }}-Tests

      # Run Tests
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ${{ matrix.projectPath }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: artifacts-${{ matrix.unityVersion }}-${{ matrix.testMode }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.unityVersion }}-${{ matrix.testMode }} Test Results
          coverageOptions: 'useProjectSettings;generateHtmlReport;generateBadgeReport;generateAdditionalMetrics'
      
      # Artifacts
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results for ${{ matrix.unityVersion }}-${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results for ${{ matrix.unityVersion }}-${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}
